"""empty message

Revision ID: 98b4d37b3bb8
Revises: bd542615a1d2
Create Date: 2022-05-03 18:59:29.666967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b4d37b3bb8'
down_revision = 'bd542615a1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('climate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'climate')
    # ### end Alembic commands ###
